version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ./app.env
    ports:
      - 5434:5432
    volumes:
      - ./pgaesthetic:/var/lib/docker/volumes/pgaesthetic/_data
    networks:
      - database-net

  goapp:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - "8080:8000"
    environment:
      - REDIS_ADDR=redis:6379
      - GOPATH=/go
      - GO111MODULE=on
      - CGO_ENABLED=0
    volumes:
      - .:/go/src/aestheticProjectBE
    command: go run cmd/server/main.go
    depends_on:
      - postgres

volumes:
  redisDB:
  postgresDB:

networks:
  database-net:
    external: true
