version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ./pg.env
    ports:
      - 5434:5432
    volumes:
      - ./pgaesthetic:/var/lib/docker/volumes/pgaesthetic/_data
    networks:
      - database-net

  goapp:
    build:
      context: ./ # Adjust the context to point to the root directory
      dockerfile: ./cmd/server/Dockerfile # Adjust the path to the Dockerfile
    ports:
      - "8080:8000"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres

volumes:
  redisDB:
  postgresDB:

networks:
  database-net:
    external: true
